In [1]:
import numpy as np
from scipy.linalg import qr

# 4.1

In [2]:
A = np.array([[1,2,3],
             [1,np.sqrt(3), 3],
             [1, np.sqrt(5), 3],
             [np.sqrt(13), 2, 3]])
# CPQR Factorization
Q, R, P = qr(A, mode='economic', pivoting=True)
Q

array([[-5.00000000e-01, -2.88675135e-01, -2.97984627e-02],
       [-5.00000000e-01, -2.88675135e-01,  7.21534950e-01],
       [-5.00000000e-01, -2.88675135e-01, -6.91736487e-01],
       [-5.00000000e-01,  8.66025404e-01, -1.05266750e-16]])

In [3]:
# Rank-1 approximation
# First column of Q and first row of R
q1 = Q[:, 0]  # first column of Q
r1 = R[0, :]  # first row of R

# Reconstruct the rank-1 approximation using the outer product
rank_1_approximation = np.outer(q1, r1)

# Apply the column permutation
P_inv = np.argsort(P)  # inverse permutation to reorder columns
rank_1_approximation = rank_1_approximation[:, P_inv]

print("Rank-1 approximation:")
print(rank_1_approximation)

Rank-1 approximation:
[[1.65138782 1.9920297  3.        ]
 [1.65138782 1.9920297  3.        ]
 [1.65138782 1.9920297  3.        ]
 [1.65138782 1.9920297  3.        ]]


3, 1.6, 1.9

# 4.2

The non-zero singular values of this matrix are approximately 15.7784 and 6.2356.

In [4]:
from scipy.linalg import lstsq

A = np.array([[9,0,5,2],
             [-7.2,0,-6,0],
             [6,0,0,4],
             [3,0,5,-2]])

k = 2


J = [0,2]
Jp = [1,3]
P_index = J + Jp
m, n = A.shape
P = np.eye(n)[:,P_index]

#  QR decomposition with column pivoting
# Q is orthogonal, R is upper triangular, P contains the permutation indices
Q, R = np.linalg.qr(A@P)

# T = R1^{-1} * R2
R1 = R[:k, :k]  # Upper triangular matrix for first k columns
R2 = R[:k, k:]  # R2 is the rest of the first k rows
R3 = R[k:, k:]  # Remaining rows and columns
T = np.linalg.inv(R1) @ R2  # Matrix T

# Z = [I_k, T]
I_k = np.eye(k)  # Identity matrix of size k
Z = np.hstack([I_k, T]) @ P.T  # Horizontal stack of I_k and T
C = A[:,J]


# Approximation of A
approx_A = C @ Z

# Approximation error
approximation_error = np.linalg.norm(A - approx_A)
approx_A
Z

array([[ 1.        ,  0.        ,  0.        ,  0.66666667],
       [ 0.        ,  0.        ,  1.        , -0.8       ]])

In [5]:
# Select specific column indices J and row indices I
J = [0, 2]  # Columns 2 and 4
I = [0, 2]  # Rows 2 and 4

# Create C and R matrices by selecting columns and rows
C = A[:, J]  # Selected columns
R = A[I, :]  # Selected rows

# Compute the submatrix A_IJ for the selected rows and columns
A_IJ = A[I,:][:,J]

# Step 2: Compute the pseudoinverse of A_IJ using Moore-Penrose pseudoinverse
U = np.linalg.pinv(A_IJ)

# Step 3: Construct the CUR decomposition
CUR = C @ U @ R

print("CUR Decomposition:")
print(CUR)

CUR Decomposition:
[[ 9.00000000e+00  0.00000000e+00  5.00000000e+00  2.00000000e+00]
 [-7.20000000e+00  0.00000000e+00 -6.00000000e+00  4.44089210e-16]
 [ 6.00000000e+00  0.00000000e+00  8.32667268e-16  4.00000000e+00]
 [ 3.00000000e+00  0.00000000e+00  5.00000000e+00 -2.00000000e+00]]


In [6]:
print("C:")
print(C)
print("U:")
print(U)
print("R:")
print(R)

C:
[[ 9.   5. ]
 [-7.2 -6. ]
 [ 6.   0. ]
 [ 3.   5. ]]
U:
[[ 2.77555756e-17  1.66666667e-01]
 [ 2.00000000e-01 -3.00000000e-01]]
R:
[[9. 0. 5. 2.]
 [6. 0. 0. 4.]]


In [7]:
import pandas as pd
pd.DataFrame(U)

0         1
0  2.775558e-17  0.166667
1  2.000000e-01 -0.300000

# 4.3 Schur Decomposition

In [ ]:
from scipy.linalg import schur

# Define the square matrix A
A = np.array([[7, -2],
              [12, -3]])

'''v = np.array([1,2])/np.sqrt(5)
v0 = np.array([-2,1])

# Compute Schur decomposition
U, T = schur(A)

# Display Q and T matrices
U, T  # Unitary matrix Q and upper triangular matrix T'''
eigenvalues, eigenvectors = np.linalg.eig(A)
eigenvectors, eigenvalues

Eigevalue decomposition:

$$ \lambda_{1} = 3, \lambda_{2} = 1$$ 

$$
\begin{pmatrix}
1 & 1 \\
2 & 3 \\
\end{pmatrix}
$$

In [ ]:
import numpy as np
V = np.array([[1,1],
             [2,3]])
V_t = V.T
D = np.array([[3,0],
             [0,1]])

V @ D @ V_t

T = UAU*
U = saco eigenvalues, el vector normalizado del mayor eigenvalue (3)
= v1 x [-2,1].T