In [2]:
import numpy as np

# 2.1
-------------------------------------

In [3]:
A = np.array([[1,0,1],
             [-1,1,0]])

# Perform SVD
U, S, VT = np.linalg.svd(A, full_matrices=True)

In [4]:
# Adjust VT to have a negative element at VT[2,2]
if VT[2, 2] >= 0:
    VT[2, :] *= -1

# S will remain unchanged as it's the diagonal matrix of singular values

# Print adjusted matrices
print("U")
print(U)
print("Sigma")
diagonal_S = np.diag(S)
print(diagonal_S)
print("Adjusted VT where VT[2,2] is negative:")
print(VT)

U
[[ 0.70710678  0.70710678]
 [-0.70710678  0.70710678]]
Sigma
[[1.73205081 0.        ]
 [0.         1.        ]]
Adjusted VT where VT[2,2] is negative:
[[ 8.16496581e-01 -4.08248290e-01  4.08248290e-01]
 [-4.40677305e-16  7.07106781e-01  7.07106781e-01]
 [ 5.77350269e-01  5.77350269e-01 -5.77350269e-01]]


In [46]:
import pandas as pd
df_vt = pd.DataFrame(VT)
df_vt

0         1         2
0  8.164966e-01 -0.408248  0.408248
1 -4.406773e-16  0.707107  0.707107
2  5.773503e-01  0.577350 -0.577350

In [39]:
# Compute the Spectral Norm (maximum singular value)
spectral_norm = np.max(S)

# Compute the Frobenius Norm (square root of sum of squares of the singular values)
frobenius_norm = np.sqrt(np.sum(S**2))

print(f"Spectral Norm of A: {spectral_norm}")
print(f"Frobenius Norm of A: {frobenius_norm}")

Spectral Norm of A: 1.732050807568877
Frobenius Norm of A: 1.9999999999999998


In [21]:
# Get the first singular value, and the first left and right singular vectors
sigma1 = S[0]
u1 = U[:, 0]
v1 = VT[0, :]

# Compute the rank-1 approximation of A
A1 = sigma1 * np.outer(u1, v1)

print("Rank-1 approximation of A:")
print(A1)

Rank-1 approximation of A:
[[ 1.  -0.5  0.5]
 [-1.   0.5 -0.5]]


# 2.2
----------------------------------------------

In [5]:
A = np.array([[-2,11],
             [-10,5]])

We define the matrix $A$ as follows:

$$
A = \begin{bmatrix}
    -2 & 11 \\
    -10 & 5
\end{bmatrix}$$

The singular value decomposition would be:
$$
U = \begin{bmatrix}
    \frac{1}{\sqrt{2}} & \frac{1}{\sqrt{2}} \\
    \frac{1}{\sqrt{2}} & -\frac{1}{\sqrt{2}}\end{bmatrix}
$$

$$
\Sigma = \begin{bmatrix}
    10\sqrt{2} & 0 \\
    0 & 5\sqrt{2}
\end{bmatrix}
$$

$$
V = \begin{bmatrix}
    -\frac{3}{5} & \frac{4}{5} \\
    \frac{4}{5} & \frac{3}{5}
\end{bmatrix}
$$

In [6]:
# Calculate the inverse of the matrix
A_inv = np.linalg.inv(A)

# Print the inverse
print(A_inv)

[[ 0.05 -0.11]
 [ 0.1  -0.02]]


In [56]:
# Calculate the eigenvalues and eigenvectors of the matrix
eigenvalues, eigenvectors = np.linalg.eig(A)

# Print the eigenvalues
print(eigenvalues)

[1.5+9.88685997j 1.5-9.88685997j]


In [57]:
eigenvectors

array([[0.72374686+0.j        , 0.72374686-0.j        ],
       [0.23028309+0.65050763j, 0.23028309-0.65050763j]])

eigenvalues:
$$
\lambda_{1} = \frac{1}{2}(3 + i \sqrt{391})
$$

$$
\lambda_{2} = \frac{1}{2}(3- i \sqrt{391})
$$

In [58]:
# Perform SVD to get the singular values
U, S, VT = np.linalg.svd(A)

# The singular values are the lengths of the semi-axes of the ellipsoid
sigma_1, sigma_2 = S

# Calculate the area of the ellipsoid
area_ellipsoid = np.pi * sigma_1 * sigma_2

print("Area of the ellipsoid:", area_ellipsoid)

Area of the ellipsoid: 314.1592653589792
