In [1]:
import numpy as np

# 1.1

In [2]:
# Step 3: Define your matrix
A = np.array([[1, -1, 4],
              [3, 2, -1],
              [2, 1, -1]])

# Step 4: Compute the eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)

# Step 5: Access and print the eigenvalues and eigenvectors
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:", eigenvectors)

Eigenvalues: [ 3. -2.  1.]
Eigenvectors: [[ 0.40824829  0.57735027  0.23570226]
 [ 0.81649658 -0.57735027 -0.94280904]
 [ 0.40824829 -0.57735027 -0.23570226]]


In [3]:
diagonal_matrix = np.diag(eigenvalues)

print("Diagonal matrix using the eigenvalues:")
print(diagonal_matrix)

Diagonal matrix using the eigenvalues:
[[ 3.  0.  0.]
 [ 0. -2.  0.]
 [ 0.  0.  1.]]


In [4]:
# check if A is V(diag)V-1
V = np.array([[1, -1,-1], 
              [2, 1,4],
             [1,1,1]])
V = eigenvectors
V_inv = np.linalg.inv(V)

V @ diagonal_matrix @ V_inv

array([[ 1., -1.,  4.],
       [ 3.,  2., -1.],
       [ 2.,  1., -1.]])

----------------------------------

# 1.2

In [5]:
A = np.ones((4,4))
A

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [6]:
# a) Eigenvalues A- I4
'''
(a) The eigenvalues of A − I4 are . . . (the smaller one) which has algebraic multiplicity
. . . , and . . . (the larger one) which has algebraic multiplicity . . . .
(b) The determinant of A − I4 is . . . .

'''
eigenvalues, eigenvectors = np.linalg.eig(A-np.eye(4))
#eigenvalues_manual = np.array([4,0,0,0])
#eigenvectors_manual = np.array([[1,1,1,1],
#                                [-1,0,0,1],
#                                [-1,0,1,0],
#                                [-1,1,0,0]]).T
eigenvalues

array([-1.,  3., -1., -1.])

In [7]:
round(np.linalg.det(A-np.eye(4)))

-3

-------------------------------------

# 1.3

In [8]:
A = np.array([[1,2,0,2,-1,1],
             [3,6,1,1,-2,1],
             [5,10,1,5,-4,3]])
A

array([[ 1,  2,  0,  2, -1,  1],
       [ 3,  6,  1,  1, -2,  1],
       [ 5, 10,  1,  5, -4,  3]])

a) Find a basis for the range of A) 
.

In [9]:
row_echelon_A = np.array([[1, 2, 0, 2, -1, 1], [0, 0, 1, -5, 1, -2], [0, 0, 0, 0, 0, 0]])
row_echelon_A

array([[ 1,  2,  0,  2, -1,  1],
       [ 0,  0,  1, -5,  1, -2],
       [ 0,  0,  0,  0,  0,  0]])

From the povits get that 1,0,0 and 0,1,1 (because last row is equal to second to last row)

b) The range(A) is a range in R3, which equation is.

−2x−y+z=0

c) The dimension of the row space of A is�
A is 2.

d) Fill in the missing coordinates of the following vector so that it lies in the row space  of A.

```K = [4,_,6,_,_,_].T```

In [10]:
basis_1 = np.array([3, 6, 1, 1, -2, 1])
basis_2 = np.array([1, 2, 0, 2, -1, 1])

# Vector to check
v = np.array([4, 8, 6, -22, 2, -8])

# Form the matrix from the basis vectors
B = np.vstack([basis_1, basis_2]).T  # Ensure B is correctly oriented

# Solve the least squares problem Bx = v to find the coefficients x
x, residuals, rank, s = np.linalg.lstsq(B, v, rcond=None)

# If the residuals are small or zero, v lies in the row space
is_in_row_space = residuals.size == 0 or np.isclose(residuals, 0)

print("Vector lies in the row space:", is_in_row_space)
print("Coefficients:", x)

Vector lies in the row space: [ True]
Coefficients: [  6. -14.]


# 1.4

In [11]:
A = np.array([[1/3,-2/3,-2/3],
             [-2/3,5/6,-7/6],
             [-2/3,-7/6,5/6]])
A

array([[ 0.33333333, -0.66666667, -0.66666667],
       [-0.66666667,  0.83333333, -1.16666667],
       [-0.66666667, -1.16666667,  0.83333333]])

In [12]:
eigenvalues, eigenvectors = np.linalg.eig(A)
eigenvalues

array([ 1., -1.,  2.])

In [13]:
V = eigenvectors

V / V[0]

array([[ 1.0000000e+00,  1.0000000e+00,  1.0000000e+00],
       [-5.0000000e-01,  1.0000000e+00, -2.3474106e+16],
       [-5.0000000e-01,  1.0000000e+00,  2.3474106e+16]])

In [14]:
V / V[1]

array([[-2.00000000e+00,  1.00000000e+00, -4.26001314e-17],
       [ 1.00000000e+00,  1.00000000e+00,  1.00000000e+00],
       [ 1.00000000e+00,  1.00000000e+00, -1.00000000e+00]])

In [15]:
V / V[2]

array([[-2.00000000e+00,  1.00000000e+00,  4.26001314e-17],
       [ 1.00000000e+00,  1.00000000e+00, -1.00000000e+00],
       [ 1.00000000e+00,  1.00000000e+00,  1.00000000e+00]])

a) Characteristic polynomial
$ p(\lambda) =  - \lambda^3 + 2 \lambda^2 + \lambda - 2$ ???

b) Eigenvalues eigenvectors]]

In [16]:
l1 = 2
l2 = -1
l3 = 1
v1 = np.array([0,-1,1])
v2 = np.array([1,1,1])
v3 = np.array([-2,1,1])

In [20]:
a, b, c, d, m, n = 1, 4 ,2, 0, -3, 6

In [21]:
# Checking the results:


E_1 = 1/m * np.array([[ a, a, a],
                      [ a, a, a],
                      [ a, a, a]])

E_2 = 1/n * np.array([[ b, -c, -c],
                      [-c,  a,  a],
                      [-c,  a,  a]])

E_3 = 1/2 * np.array([[ d,  d,  d],
                      [ d, a, -a],
                      [ d, -a,  a]])

check = (1*E_1) + (1*E_2) + (2*E_3) - A
check

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])