In [6]:
import numpy as np
import pandas as pd

# 6.1 Power Method

Apply the power method (using the euclidean norm for scaling) to the matrix A, starting with x(0) and stopping at x(4). Compare the resulting approximations to the exact values of the dominant eigenvalue and the corresponding unit eigenvector

$x^k = A x^{k-1}$


$x^k = A^k x^{0}$

In [7]:
A = np.array([[2,1],
             [1,1]])
x0 = np.array([[1],
              [0]])
x0.shape

(2, 1)

In [8]:
np.linalg.norm(x0)

1.0

In [9]:
def simple_vector_iteration(A, x0, tol=1e-6, max_iter=1000):
    # Initialize variables
    x = x0
    k = 0
    
    while True:
        # Increment iteration counter
        k += 1
        
        # Compute y^(k) = A * x^(k-1)
        y = np.dot(A, x)
        
        # Compute the Euclidean norm mu_k = ||y^(k)||
        mu = np.linalg.norm(y)
        
        # Compute the next iterate x^(k) = y^(k) / mu_k
        x_next = y / mu
        
        # Check for convergence
        if np.linalg.norm(x_next - x) < tol or k >= max_iter:
            break
        
        # Update x for the next iteration
        x = x_next
        
    return x, mu, k

In [10]:
x1,mu, k1 = simple_vector_iteration(A, x0, tol=1e-6, max_iter=1)
x2,mu, k2 = simple_vector_iteration(A, x0, tol=1e-6, max_iter=2)
x3,mu, k3 = simple_vector_iteration(A, x0, tol=1e-6, max_iter=3)
x4,mu, k4 = simple_vector_iteration(A, x0, tol=1e-6, max_iter=4)
x5,mu, k5 = simple_vector_iteration(A, x0, tol=1e-6, max_iter=5)

x5

array([[0.850798  ],
       [0.52549288]])

In [11]:
x4,mu, k4 = simple_vector_iteration(A, x0, tol=1e-6, max_iter=4)
x4

array([[0.85165832],
       [0.52409743]])

Exact eigenvalues:

$ \lambda_1 = \frac{1}{2} (3 + \sqrt{5}) = 2.61803$

$ \lambda_2 = \frac{1}{2} (3 - \sqrt{5}) = 0.381966$

Eigenvectors

$v_1 = (\frac{1}{2}(1+\sqrt{5}),1) = (1,611803,1)$

$v_2 = (\frac{1}{2}(1-\sqrt{5}),1) = (-0.618034,1)$

In [12]:
# Compute the exact eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)

# Identify the dominant eigenvalue and corresponding eigenvector
dominant_index = np.argmax(np.abs(eigenvalues))
dominant_eigenvalue = eigenvalues[dominant_index]
dominant_eigenvector = eigenvectors[:, dominant_index]

# Normalize the exact dominant eigenvector
dominant_eigenvector = dominant_eigenvector / np.linalg.norm(dominant_eigenvector)

print("Exact dominant eigenvalue:")
print(dominant_eigenvalue)
print("Exact dominant eigenvector:")
print(dominant_eigenvector)

# Compare the results
print("Comparison of eigenvalues:")
print(f"Approximated: {mu}")
print(f"Exact: {dominant_eigenvalue}")

print("Comparison of eigenvectors:")
print(f"Approximated: {x4.flatten()}")
print(f"Exact: {dominant_eigenvector}")

Exact dominant eigenvalue:
2.618033988749895
Exact dominant eigenvector:
[0.85065081 0.52573111]
Comparison of eigenvalues:
Approximated: 2.61802926897674
Exact: 2.618033988749895
Comparison of eigenvectors:
Approximated: [0.85165832 0.52409743]
Exact: [0.85065081 0.52573111]


# 6.2 Pagerank

Compute the ranking of the following network using the transition matrix S as well as the modified Google matrix G (PageRank) introduced in the lecture. Which node is the most relevant?

In [36]:
# Define the adjacency matrix A
A = np.array([[0, 1, 0, 0,0],
              [0, 0, 1, 1,0],
              [1, 0, 0, 0,0],
              [1, 0, 1, 0,1],
              [1, 1, 1, 0,0]])

# Calculate the degree of each node (sum of each row)
degrees = np.sum(A, axis=1)

# Construct the Degree matrix D
D = np.diag(degrees)

print("Adjacency matrix A:")
print(A)
print("Degree matrix D:")
print(D)

Adjacency matrix A:
[[0 1 0 0 0]
 [0 0 1 1 0]
 [1 0 0 0 0]
 [1 0 1 0 1]
 [1 1 1 0 0]]
Degree matrix D:
[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 1 0 0]
 [0 0 0 3 0]
 [0 0 0 0 3]]


### Pagerank with S

In [37]:
# Calculate the out-degree of each node (sum of each row)
out_degrees = np.sum(A, axis=1)

# Number of nodes
n = A.shape[0]

# Initialize the stochastic matrix S with zeros
S = np.zeros_like(A, dtype=float)

# Construct the stochastic matrix S
for i in range(n):
    for j in range(n):
        if A[i, j] == 1:
            S[j, i] = 1 / out_degrees[i]

print("Stochastic matrix S:")
print(S)

# Calculate the eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(S)

# Find the eigenvector corresponding to the eigenvalue 1
# Due to numerical precision, we check for eigenvalues close to 1
index = np.argmax(np.abs(eigenvalues - 1))
dominant_eigenvector = np.abs(eigenvectors[:, index])

# Normalize the dominant eigenvector to sum to 1
pagerank_vector = dominant_eigenvector / np.sum(dominant_eigenvector)

print("PageRank vector:")
print(pagerank_vector)

# Determine the most important node
most_important_node = np.argmax(pagerank_vector)
print(f"The most important node is: {most_important_node}")

Stochastic matrix S:
[[0.         0.         1.         0.33333333 0.33333333]
 [1.         0.         0.         0.         0.33333333]
 [0.         0.5        0.         0.33333333 0.33333333]
 [0.         0.5        0.         0.         0.        ]
 [0.         0.         0.         0.33333333 0.        ]]
PageRank vector:
[0.25005105 0.32704757 0.15063612 0.19486271 0.07740255]
The most important node is: 1


In [38]:
out_degrees

array([1, 2, 1, 3, 3])

In [39]:
D = np.diag(out_degrees)
D

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 3]])

In [40]:
A.T @ np.linalg.inv(D)

array([[0.        , 0.        , 1.        , 0.33333333, 0.33333333],
       [1.        , 0.        , 0.        , 0.        , 0.33333333],
       [0.        , 0.5       , 0.        , 0.33333333, 0.33333333],
       [0.        , 0.5       , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.33333333, 0.        ]])

In [42]:
# Calculate the eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(S)

# Find the eigenvector corresponding to the eigenvalue 1
# Due to numerical precision, we check for eigenvalues close to 1
#index = np.argmax(np.abs(eigenvalues - 1))
dominant_eigenvector = eigenvectors[:, 0]
dominant_eigenvector
#eigenvalues

array([0.57569264+0.j, 0.60955692+0.j, 0.44023555+0.j, 0.30477846+0.j,
       0.10159282+0.j])

In [43]:
normalized_eigenvect = dominant_eigenvector / np.sum(dominant_eigenvector)
normalized_eigenvect

array([0.28333333+0.j, 0.3       +0.j, 0.21666667+0.j, 0.15      +0.j,
       0.05      +0.j])

### Pagerank with G

In [44]:
# Calculate the out-degree of each node (sum of each row)
out_degrees = np.sum(A, axis=1)

# Number of nodes
n = A.shape[0]

# Initialize the transition matrix S with zeros
S = np.zeros_like(A, dtype=float)

# Construct the transition matrix S
for i in range(n):
    if out_degrees[i] == 0:
        S[i] = np.ones(n) / n  # Dangling node handling
    else:
        S[i] = A[i] / out_degrees[i]

# Transpose to get the column-stochastic form
S = S.T

# Initialize the teleportation factor alpha
alpha = 0.85

# Create the Google matrix G
G = alpha * S + (1 - alpha) / n * np.ones((n, n))

# Initialize the PageRank vector with equal probability
p = np.ones(n) / n

# PageRank iteration
tol = 1e-6  # tolerance for convergence
max_iter = 100  # maximum number of iterations
for i in range(max_iter):
    p_new = np.dot(G, p)
    if np.linalg.norm(p_new - p, ord=1) < tol:
        break
    p = p_new

# Normalize the PageRank vector to ensure it sums to 1
p = p / np.sum(p)

print("PageRank vector:")
print(p)

# Determine the most important node
most_important_node = np.argmax(p)
print(f"The most important node is: {most_important_node}")


PageRank vector:
[0.27598951 0.28523133 0.21470952 0.15122311 0.07284652]
The most important node is: 1


In [67]:
S

array([[0.        , 0.        , 1.        , 0.33333333, 0.33333333],
       [1.        , 0.        , 0.        , 0.        , 0.33333333],
       [0.        , 0.5       , 0.        , 0.33333333, 0.33333333],
       [0.        , 0.5       , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.33333333, 0.        ]])

In [68]:
G

array([[0.03      , 0.03      , 0.88      , 0.31333333, 0.31333333],
       [0.88      , 0.03      , 0.03      , 0.03      , 0.31333333],
       [0.03      , 0.455     , 0.03      , 0.31333333, 0.31333333],
       [0.03      , 0.455     , 0.03      , 0.03      , 0.03      ],
       [0.03      , 0.03      , 0.03      , 0.31333333, 0.03      ]])

In [47]:
# Calculate the eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(G)

# Find the eigenvector corresponding to the eigenvalue 1
# Due to numerical precision, we check for eigenvalues close to 1
index = np.argmax(np.abs(eigenvalues - 1))
dominant_eigenvector = np.abs(eigenvectors[:, index])
dominant_eigenvector
normalized_eigenvector = dominant_eigenvector / np.sum(dominant_eigenvector)
normalized_eigenvector

array([0.25005105, 0.32704757, 0.15063612, 0.19486271, 0.07740255])

### Implemented PageRank

In [48]:
# Pagerank scikitnetwork
from sknetwork.ranking import PageRank

# Initialize PageRank with a damping factor (default is 0.85)
pagerank = PageRank(damping_factor=0.85)

# Compute the PageRank scores
scores = pagerank.fit_predict(A)

print("PageRank scores:")
print(scores)

# Determine the most important node
most_important_node = np.argmax(scores)
print(f"The most important node is: {most_important_node}")

PageRank scores:
[0.27619728 0.28255309 0.21581353 0.15230502 0.07313109]
The most important node is: 1


# 6.3 PageRank Influencers

You are the sales manager of an online fashion trader and decide to hire a new social
media influencer for your next advertising campaign.

Thanks to your mathematical background you don’t want to hire the influencer with the
highest number of followers but rather according to a criterion based on a popularity
ranking similar to PageRank. You have the following data:

* Influencer 1 likes his own Instagram account and the one of Influencer 2.
* Influencer 2 likes the sites of Influencer 1 and 3.
* Influencer 3 gives his likes to 2, 3 and 4.
* Influencer 4 likes 1, 3 and 4.

There are no differences between single likes, each like will be given the same weight.

a) According to your model and your ranking, which influencer shall be hired?

b) Looking at the transition matrix S you derived in a), would you expect the vector iteration

$$
x^{k+1} = Sx^k,  k = 0,1,2...
$$
to converge?

In [51]:
# Define the adjacency matrix A
A = np.array([[1,1,0,0],
             [1,0,1,0],
             [0,1,1,1],
             [1,0,1,1]])

# Calculate the degree of each node (sum of each row)
degrees = np.sum(A, axis=1)

# Construct the Degree matrix D
D = np.diag(degrees)

print("Adjacency matrix A:")
print(A)
print("Degree matrix D:")
print(D)

Adjacency matrix A:
[[1 1 0 0]
 [1 0 1 0]
 [0 1 1 1]
 [1 0 1 1]]
Degree matrix D:
[[2 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 3]]


In [55]:
# Calculate the out-degree of each node (sum of each row)
out_degrees = np.sum(A, axis=1)

# Number of nodes
n = A.shape[0]

# Initialize the stochastic matrix S with zeros
S = np.zeros_like(A, dtype=float)

# Construct the stochastic matrix S
for i in range(n):
    for j in range(n):
        if A[i, j] == 1:
            S[j, i] = 1 / out_degrees[i]

print("Stochastic matrix S:")
print(S)

# Calculate the eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(S)

# Find the eigenvector corresponding to the eigenvalue 1
# Due to numerical precision, we check for eigenvalues close to 1
#index = np.argmax(np.abs(eigenvalues - 1))
dominant_eigenvector = np.abs(eigenvectors[:, 1])

# Normalize the dominant eigenvector to sum to 1
pagerank_vector = dominant_eigenvector / np.sum(dominant_eigenvector)

print("PageRank vector:")
print(pagerank_vector)

# Determine the most important node
most_important_node = np.argmax(pagerank_vector)
print(f"The most important node is: {most_important_node}")

print('EIGENVALUES:',eigenvalues)

Stochastic matrix S:
[[0.5        0.5        0.         0.33333333]
 [0.5        0.         0.33333333 0.        ]
 [0.         0.5        0.33333333 0.33333333]
 [0.         0.         0.33333333 0.33333333]]
PageRank vector:
[0.34782609 0.26086957 0.26086957 0.13043478]
The most important node is: 0
EIGENVALUES: [-0.51983778  1.          0.23860452  0.44789993]


In [53]:
dominant_eigenvector

array([0.4212969 , 0.72813897, 0.50359709, 0.19675502])

In [76]:
from sknetwork.ranking import PageRank
# Initialize PageRank with a damping factor (default is 0.85)
pagerank = PageRank(damping_factor=0.88)

# Compute the PageRank scores
scores = pagerank.fit_predict(A)

print("PageRank scores:")
print(scores)

# Determine the most important node
most_important_node = np.argmax(scores)
print(f"The most important node is: {most_important_node}")

PageRank scores:
[0.33198044 0.25326712 0.26308039 0.15167205]
The most important node is: 0


### Try the power iteration on this model

In [77]:
import numpy as np

# Pagerank function
def pagerank(A, tol=1e-6, max_iter=1000):
    # Calculate the out-degree of each node (sum of each row)
    out_degrees = np.sum(A, axis=1)

    # Number of nodes
    n = A.shape[0]

    # Initialize the stochastic matrix S with zeros
    S = np.zeros_like(A, dtype=float)

    # Construct the stochastic matrix S
    for i in range(n):
        for j in range(n):
            if A[i, j] == 1:
                S[j, i] = 1 / out_degrees[i]

    print("Stochastic matrix S:")
    print(S)

    # Initialize x0 as a vector where all entries are equal and sum to 1
    x0 = np.ones(n) / n

    # Vector iteration method
    x, mu, k = simple_vector_iteration(S, x0, tol, max_iter)

    # Normalize the result to sum to 1
    pagerank_vector = x / np.sum(x)

    print("PageRank vector:")
    print(pagerank_vector)

    # Determine the most important node
    most_important_node = np.argmax(pagerank_vector)
    print(f"The most important node is: {most_important_node}")

    return pagerank_vector, most_important_node

# Vector iteration method
def simple_vector_iteration(A, x0, tol=1e-6, max_iter=1000):
    # Initialize variables
    x = x0
    k = 0
    
    while True:
        # Increment iteration counter
        k += 1
        
        # Compute y^(k) = A * x^(k-1)
        y = np.dot(A, x)
        
        # Compute the Euclidean norm mu_k = ||y^(k)||
        mu = np.linalg.norm(y)
        
        # Compute the next iterate x^(k) = y^(k) / mu_k
        x_next = y / mu
        
        # Check for convergence
        if np.linalg.norm(x_next - x) < tol or k >= max_iter:
            break
        
        # Update x for the next iteration
        x = x_next
        
    return x, mu, k

# Example usage with an adjacency matrix A
A = np.array([[0, 1, 1, 0],
              [1, 0, 1, 1],
              [1, 1, 0, 1],
              [0, 1, 1, 0]])

pagerank_vector, most_important_node = pagerank(A)


Stochastic matrix S:
[[0.         0.33333333 0.33333333 0.        ]
 [0.5        0.         0.33333333 0.5       ]
 [0.5        0.33333333 0.         0.5       ]
 [0.         0.33333333 0.33333333 0.        ]]
PageRank vector:
[0.20000012 0.29999988 0.29999988 0.20000012]
The most important node is: 1
